{% set name = "spyder" %}
{% set version = "3.1.2" %}
{% set sha256 = "89a98164e0d27ede273c2b50c8c05044add66c55ab733634d972e1cc55448371" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    entry_points:
        - spyder = spyder.app.start:main
    number: '0'
    osx_is_app: 'True'

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt
    - qtpy >=1.1
    - qtawesome
    - rope
    - pyflakes
    - jedi >=0.8
    - qtconsole >=4.2
    - pickleshare
    - nbconvert
    - pygments >=2.0
    - sphinx
    - pep8
    - psutil
    - pylint
    - pyzmq
    - python.app  # [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

app:
  entry: spyder
  icon: logo.png
  summary: Scientific Python Development Environment
  type: desk

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
  license_file: LICENSE
  summary: Scientific PYthon Development EnviRonment
  description: |
    Spyder is a powerful interactive development environment for the Python
    language with advanced editing, interactive testing, debugging and
    introspection features. Additionally, Spyder is a numerical computing
    environment thanks to the support of IPython and popular Python libraries
    such as NumPy, SciPy, or matplotlib.
  doc_url: http://pythonhosted.org/spyder/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
