{% set version = "6.1.0" %}
{% set name = "spyder" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5200c6249bb037307455f00c80633f50884d6ab43a75ad7c5ca13d2462574636
  patches:
    - patches/0001-transition-to-the-use-of-pyqt6.patch

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true
  no_link:
    - 'Menu/{{ name }}_menu.json'

requirements:
  build:
    - patch  # [not win]
    - msys2-patch  # [win]
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - packaging
  run:
   - python
   - python.app                        # [osx]
   # This is here to work around a bug in mamba
   - ptyprocess >=0.5                  # [win]
   - aiohttp >=3.11.2
   - applaunchservices >=0.3.0         # [osx]
   - asyncssh >=2.14.0,<3.0.0
   - atomicwrites >=1.2.0
   - bcrypt >=4.3.0
   - chardet >=2.0.0
   - cloudpickle >=0.5.0
   - cookiecutter >=1.6.0
   - diff-match-patch >=20181111
   - importlib-metadata >=4.6.0        # [py<310]
   - intervaltree >=3.0.2
   - ipython >=8.15.0,<10.0.0,!=8.17.1,!=9.1.0,!=9.2.0,!=9.3.0,!=9.4.0
   - ipython_pygments_lexers >=1.0
   - jedi >=0.17.2,<0.20.0
   - jellyfish >=0.7
   - jsonschema >=3.2.0
   - keyring >=17.0.0
   - nbconvert >=4.0
   - numpydoc >=0.6.0
   - packaging >=20.0
   - parso >=0.7.0,<0.9.0
   - pexpect >=4.4.0
   - pickleshare >=0.4
   - psutil >=5.3
   - pygithub >=2.3.0
   - pygments >=2.0
   - pylint >=3.1,<4
   - pylint-venv >=3.0.2
   - pyls-spyder >=0.4.0
   - python-lsp-black >=2.0.0,<3.0.0
   - python-lsp-ruff>=2.3.0,<3.0.0
   - python-lsp-server >=1.13.0,<1.14.0
   - pyuca >=1.2
   - pyxdg >=0.26                      # [linux]
   - pyzmq >=24.0.0
   - qdarkstyle >=3.2.0,<3.3.0
   - qstylizer >=0.2.2
   - qtawesome >=1.4.0,<1.5.0
   - qtpy >=2.4.0
   - rtree >=0.9.7
   - sphinx >=0.6.6
   - spyder-kernels >=3.1.0,<3.2.0
   - superqt >=0.6.2,<1.0.0
   - textdistance >=4.2.0
   - three-merge >=0.1.1
   - watchdog >=0.10.3
   - yarl >=1.9.4
   # qt_requirements
   - pyqt >=6.5,<7
   - pyqtwebengine >=6.5,<7
   - qtconsole >=5.7.0,<5.8.0
   # python-lsp-server[all]
   # bounds set in package python-lsp-server
   - autopep8
   - flake8
   - mccabe
   - pycodestyle
   - pydocstyle
   - pyflakes
   - pylint
   - rope
   - yapf
   - whatthepatch
  run_constrained:
    - menuinst >=2.3.1

test:
  # NOTE: Since this is a GUI application, built packages should be uploaded to
  # a staging channel and manual testing performed before releasing to
  # defaults; at the very least, you should ensure the application start,
  # editing more or less works, and the iPython console works.
  requires:
    - pip
  commands:
    - pip check
    # on linux we don't have working X11 on builder
    - USER=test spyder -h || true # [unix]
    - spyder -h                   # [win]
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
  imports:
    - spyder
    - spyder.api
    - spyder.api.config
    - spyder.api.plugin_registration
    - spyder.api.plugins
    - spyder.api.shellconnect
    - spyder.api.widgets
    - spyder.app
    - spyder.config
    - spyder.plugins
    - spyder.utils
    - spyder.utils.external
    - spyder.utils.introspection
    - spyder.utils.snippets
    - spyder.widgets
{% endif %}

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - andfoy
    - steff456
  skip-lints:
    - python_build_tool_in_run
    - missing_imports_or_run_test_py
    - patch_unnecessary
    - cbc_dep_in_run_missing_from_host
