{% set version = "5.4.2" %}

package:
  name: spyder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyder/spyder-{{ version }}.tar.gz
  sha256: 2fcce04fb33b37e3f9ffd15081fe9a6fb69f5105c2d5a7f3c148c0a7ac8ac42f

build:
  number: 0
  skip: true  # [ppc64le or s390x or py<37]
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - applaunchservices >=0.3.0  # [osx]
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - cookiecutter >=1.6.0
    - diff-match-patch >=20181111
    - intervaltree >=3.0.2
    - ipython >=7.31.1,<8.0.0
    - jedi >=0.17.2,<0.19.0
    - jellyfish >=0.7
    - jsonschema >=3.2.0
    - keyring >=17.0.0
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    # Required to get SSH connections to remote kernels
    - paramiko >=2.4.0  # [win]
    - parso >=0.7.0,<0.9.0
    - pexpect >=4.4.0
    - pickleshare >=0.4
    - ptyprocess >=0.5  # [win]
    - psutil >=5.3
    - pygments >=2.0
    - pylint >=2.5.0,<3.0
    - python-lsp-black >=1.2.0
    - pyls-spyder >=0.4.0
    # Make Spyder work with PyQt 5.15, see https://github.com/spyder-ide/spyder/commit/a68e8b933b551581ed8d7504fe9430de66782927
    - pyqt >=5.6,<5.16
    # pyqtwebengine versions are available starting from 5.15+ 
    - pyqtwebengine >=5.15,<5.16
    - python.app  # [osx]
    - python-lsp-server >=1.5.0,<1.6.0
    - pyxdg >=0.26  # [linux]
    - pyzmq >=22.1.0
    - qdarkstyle >=3.0.2,<3.1.0
    - qstylizer >=0.1.10
    - qtawesome >=1.0.2
    - qtconsole >=5.3.2,<5.4.0
    - qtpy >=2.1.0
    - rtree >=0.9.7
    - setuptools >=49.6.0
    - sphinx >=0.6.6
    - spyder-kernels >=2.3.3,<2.4.0
    - textdistance >=4.2.0
    - three-merge >=0.1.1
    - watchdog >=0.10.3
    # This is here to workaround an inconsistency with flake8
    # See: https://github.com/conda-forge/flake8-feedstock/issues/52
    - importlib-metadata <4.3  # [py<38]
  run_constrained:
    - menuinst >=1.4.17

test:
  # NOTE: Since this is a GUI application, built packages should be uploaded to
  # a staging channel and manual testing performed before releasing to
  # defaults; at the very least, you should ensure the application start,
  # editing more or less works, and the iPython console works.
  requires:
    - pip
  commands:
    - pip check || true           # [not win]
    - pip check || (exit 0)         # [win]
    # on linux we don't have working X11 on builder
    - USER=test spyder -h || true # [unix]
    - spyder -h                   # [win]
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
  imports:
    - spyder
{% endif %}

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  license_url: https://github.com/spyder-ide/spyder/blob/master/LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  doc_source_url: https://github.com/spyder-ide/spyder-docs
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - andfoy
    - steff456
