travis:
  secure:
    BINSTAR_TOKEN: D+XZf1mDA6pb5lt2vDXifcUfsPdssL85B6wYTltuJ8ia8v3uCIQ/NSxPgzNNcVqyG7fGw6ymuBRlH83HbRM2ghwG3mMO320uxx15uyrc7KL13QAZSK//bWS9mUbjLSI3vNlw/1vAjhizbjlk47CUpi8yNKUqiAPL3Blll/uahlT5+TB4AeRfW6LQFWsAdv+2kUg41cT+eYECufn8yJS226kf5fSbKuLBkw96YXBNszDGLf9qPAkixZMRH6GTMcLXP7s/RbGjT0sBlEwTiU8G7fvlAfI2AT+ecU32U9QZNer4CZYIfsh77ksCCGRilh0HWA+frp6buolDePHHaZD8kA/+c9IMVzeDBGryVBdqVJnbmZUssTFri1sgp2GOVu4PLzX++iPFJA3fTDHf1M1T/oBpta9C/zJR+hiB8akeA9EfYqDxAbaMyPplwwah6qP38GL4H5l/o7jpjRg5UQSuAkKFhTg0Mwgz2+rmtaCv7GSAbChZURcdha5O3TNHdmc6z/JIkhq4OIPRTFEXKd+YKoWE1zuXziLPJABYqqBDcnscb9EXv+qKstqTbBZ71sOsmSUi9us4x0r38Pab6ham1LsF5RcGOl+GCbKJPwnp8UtlUFzxOx/fEu+hQJXLUqQ9UlZ2CLD+ZaF16TXj++7pV1/UI9G6cUsLL7jqumocJgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
