travis:
  secure:
    BINSTAR_TOKEN: Mkj+SJBZmCTcyiEUTby89mYwhe9Wg4RRSF14ewZfJIyHO/4c/Up0V/4a5ymK2wfLpnLpRylM9ZztuF15cRxh3PFkQBxQoXajlPEf/rhXlqWWoNqcib3QBWJLt8f4grhKrWPFltIdrZju+fp3Ak/3GBFSlR3PAdfdxQ97kjW8xuGdZ7P+9+9SCd/GoKiI4FQC3UK7R9NNn2izwUEud+Dir+opB7qWhXz/av9HlOXQ9e5WOXyNleY9xFMB9lPqot27t/MqAxhTrIU/N2nH3Se2V1l2rHDyjonY4gBOek7up2Bjxn+9DOL9Tm1ji+32MTsqkpvCN4l5bX3uyYctT589nVQYNK9AHM2PUsR5J/a7dPTEjILVibx/UNutqGQU0SjyMBfMpNJQPsvlnGG0p+aVEMrMh5mW4EXg0Z3u8zld6bab6fv7Bb0frpmeRqIbWogtjzJxcwVQIQzbghbwAncNMHuR7gNZX594HQQpcGFYXRFRIZs8JPnE3/Icm6ipfze+StURw0caojhFLtinhthsTUt2yciez+wsrAquCvWe9KGPd3tpv/kXc/sFGNsw7Vn/zTMBoeXH9Vt1INmzgFpPiTolQ8Sz+VI7e9lpPLcp3/oPJ+vUuYK8+nMdozqI8+8S8VT0zLieiEmAamde1NbD8mXJr/cA7K+BRzWMbZ/1wC8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
